name: Docker Multi-arch Build

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: |
          docker buildx create --use
          docker compose build --platform linux/amd64,linux/arm64 --output type=docker

      - name: Save Docker images
        run: |
          mkdir -p images
          docker save $(docker images -q) -o images/docker-images.tar

      - name: Upload images as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: images/docker-images.tar
